<a href="https://colab.research.google.com/github/anubhavgupta1/Data---Science/blob/main/Rules_of_stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats with Numpy

In [1]:
import numpy as np
import time

In [2]:
arr = np.random.rand(10000000,)

In [3]:
print("Minimum in array = ",np.amin(arr))
print("Maximum in array = ",np.amax(arr))
print("Mean of array = ",np.mean(arr))
print("Variance of array = ",np.var(arr))
print("Standard Deviation of array = ",np.std(arr))
print("Median of array = ",np.median(arr))
print("50th Percenile of array = ",np.percentile(arr, 50))
print("10th Percenile of array = ",np.percentile(arr, 10))
print("90th Percenile of array = ",np.percentile(arr, 90))

Minimum in array =  2.2119018838751003e-09
Maximum in array =  0.9999997301063213
Mean of array =  0.4999202046804808
Variance of array =  0.08337636396398453
Standard Deviation of array =  0.28874965621448717
Median of array =  0.49988392045448105
50th Percenile of array =  0.49988392045448105
10th Percenile of array =  0.09978183937185185
90th Percenile of array =  0.9000112830529324


In [4]:
%%time
print("IQR of array = ",np.percentile(arr, 75)-np.percentile(arr, 25))

IQR of array =  0.5002763218371324
CPU times: user 254 ms, sys: 2.77 ms, total: 257 ms
Wall time: 255 ms


In [5]:
%%time
quartiles = np.percentile(arr, [25,75])
print("IQR of array = ",quartiles[1]-quartiles[0])

IQR of array =  0.5002763218371324
CPU times: user 186 ms, sys: 117 µs, total: 186 ms
Wall time: 187 ms


In [6]:
z_score = (arr - np.mean(arr) )/np.std(arr)
print("Z Score of array = ",z_score)

Z Score of array =  [ 0.57125338 -1.27075782  1.0028366  ...  0.82504091 -1.56397801
 -1.61334811]


In [7]:
print(np.mean(z_score))
print(np.var(z_score))
print(np.std(z_score))

-5.350983656171593e-16
1.0000000000000013
1.0000000000000007


In [8]:
print(np.histogram(arr))

(array([1002214, 1000018,  999247,  999463, 1000210, 1000122,  997702,
       1000473, 1000441, 1000110]), array([2.21190188e-09, 9.99999750e-02, 1.99999948e-01, 2.99999921e-01,
       3.99999893e-01, 4.99999866e-01, 5.99999839e-01, 6.99999812e-01,
       7.99999785e-01, 8.99999757e-01, 9.99999730e-01]))


In [9]:
print(np.histogram(arr, bins = 5))

(array([2002232, 1998710, 2000332, 1998175, 2000551]), array([2.21190188e-09, 1.99999948e-01, 3.99999893e-01, 5.99999839e-01,
       7.99999785e-01, 9.99999730e-01]))


In [10]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])


(array([2501615, 2499537, 2497662, 2501186]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [11]:
bins = [0, 0.25, 0.5, 0.75, 1]
np.digitize(arr, bins)

array([3, 1, 4, ..., 3, 1, 1])

In [12]:
arr1 = np.random.randint(0, 10, (10))
print(arr1)
bins = [0, 6, 10]
np.digitize(arr1, bins)

[9 2 9 4 6 3 7 7 8 9]


array([2, 1, 2, 1, 2, 1, 2, 2, 2, 2])

In [13]:
np.digitize(arr1, bins, right=True)


array([2, 1, 2, 1, 1, 1, 2, 2, 2, 2])

In [14]:
arr1 = np.random.randint(50, 80, 100) # weight
arr2 = np.random.randint(150, 185, 100) # heights
arr3 = np.random.randint(17, 22, 100) # age


In [15]:
np.concatenate((arr1, arr2, arr3)).shape


(300,)

In [16]:
np.vstack((arr1, arr2, arr3)).shape


(3, 100)

In [17]:
arr2d = np.vstack((arr1, arr2, arr3))
print(np.amin(arr2d, axis=1))
print(np.amax(arr2d, axis=1))
print(np.mean(arr2d, axis=1))

[ 50 150  17]
[ 79 184  21]
[ 64.31 166.39  19.03]


# Rules of Statistics

In [18]:
arr = np.random.rand(1000)
mean = np.mean(arr)
arr1 = arr - mean
np.mean(arr1)

4.884981308350689e-17

# Computing mean with smaller set of values

In [19]:
arr = np.random.rand(1000)

In [20]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

1 0.867773127870064
2 0.714186744528563
3 0.7933227482967958
4 0.7866067122586256
5 0.7796669384549914
6 0.724682662245456
7 0.6866030499572405
8 0.6058986966747824
9 0.593546219621806
10 0.5675013359436836
11 0.6035337104497625
12 0.6012297791871556
13 0.563817314993834
14 0.5937560651517435
15 0.6175589638367887
16 0.5870501682301494
17 0.5735402824603916
18 0.5808851382423985
19 0.5723587007564181
20 0.590786903786271
21 0.57473160049515
22 0.582904828179514
23 0.5797242081003362
24 0.5966362049959469
25 0.6022468081706419
26 0.5877221961486948
27 0.597584340646636
28 0.59194389761392
29 0.5920187637609531
30 0.5928647316697612
31 0.5800603764318182
32 0.5838099110796471
33 0.581583928794865
34 0.5879138899444443
35 0.585048615149616
36 0.5905486648868501
37 0.586653177826042
38 0.5902653594559901
39 0.5878568912425117
40 0.5812370578806721
41 0.5704704151810002
42 0.5659100658661745
43 0.5713830143716836
44 0.5805141043575763
45 0.5879512290911666
46 0.5924659423779757
47 0.5917393

In [21]:
arr = np.random.randint(0,10,10)
print("array is : ", arr)
print("Cummulative sum is : ", np.cumsum(arr))

array is :  [5 4 8 7 1 8 0 2 5 6]
Cummulative sum is :  [ 5  9 17 24 25 33 33 35 40 46]


In [22]:
means = np.cumsum(np.random.rand(1000))/np.arange(1,1001)
means[0:15]

array([0.90060791, 0.94586961, 0.85662787, 0.83030559, 0.714819  ,
       0.6711479 , 0.63306026, 0.67337232, 0.6782025 , 0.65996617,
       0.63631985, 0.64444153, 0.66783938, 0.62774791, 0.60284705])

##Effect of outliers on mean and median

In [23]:
arr = np.random.randint(1, 100, 100)
print("Mean is : ", np.mean(arr))
print("Median is : ", np.median(arr))

Mean is :  48.46
Median is :  53.0


In [24]:
arr = np.append(arr, [1000, 2000])
print("Mean is : ", np.mean(arr))
print("Median is : ", np.median(arr))

Mean is :  76.92156862745098
Median is :  53.0


## Effect of scaling arrays on mean and median

In [25]:
old_arr = np.random.randint(1, 100, 100)
print("Mean is : ", np.mean(old_arr))
print("Median is : ", np.median(old_arr))
print("50th Percenile of array = ",np.percentile(old_arr, 50))
print("Min = {}, Max = {} and Range  = {}".format(np.amin(old_arr),np.amax(old_arr),np.amax(old_arr)-np.amin(old_arr)))
quartiles = np.percentile(old_arr, [25,75])
print("IQR of array = ",quartiles[1]-quartiles[0])
print("Standard deviation = ", np.std(old_arr))
print("Variance is : ", np.var(old_arr))

Mean is :  49.98
Median is :  50.0
50th Percenile of array =  50.0
Min = 2, Max = 99 and Range  = 97
IQR of array =  48.25
Standard deviation =  29.664450104460055
Variance is :  879.9796000000001


In [26]:
new_arr = 2.5 * old_arr + 0.65

In [27]:
new_mean = 2.5 * np.mean(old_arr) + 0.6
new_median = 2.5 * np.median(old_arr) + 0.6
new_percentile_50th = 2.5 * np.percentile(old_arr, 50) + 0.6


In [28]:
print("New Mean is : {}, {}".format(np.mean(new_arr), new_mean))
print("New Median is : {}, {}".format(np.median(new_arr), new_median))
print("New 50th Percenile of array is : {}, {}".format(np.percentile(new_arr, 50), new_percentile_50th))

New Mean is : 125.6, 125.54999999999998
New Median is : 125.65, 125.6
New 50th Percenile of array is : 125.65, 125.6


In [29]:
new_range = 2.5 * (np.amax(old_arr)-np.amin(old_arr))
new_iqr = 2.5 * (quartiles[1]-quartiles[0])
new_std = 2.5 * np.std(old_arr)

In [30]:
new_quartiles = np.percentile(new_arr, [25,75])

In [31]:
print("New Range  = {}, {}".format(np.amax(new_arr)-np.amin(new_arr), new_range))
print("New IQR  = {}, {}".format(new_quartiles[1]-new_quartiles[0], new_iqr))
print("New Standard Deviation = {}, {}".format(np.std(new_arr), new_std))

New Range  = 242.5, 242.5
New IQR  = 120.625, 120.625
New Standard Deviation = 74.16112526115012, 74.16112526115013


In [32]:
new_var = 2.5 * 2.5 * np.var(old_arr)

In [33]:
print("New Variance = {}, {}".format(np.var(new_arr), new_var))

New Variance = 5499.872499999998, 5499.8725
